// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcdoohlxsxqnxsptrzgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjZG9vaGx4c3hxbnhzcHRyemd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTIzNTIsImV4cCI6MjA2ODIyODM1Mn0.s86K7G3cIG2-g1SaG1zJlHLwya3t5uBoYagu8A0BmLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});